from BACKEND.models.driver import Driver, DriverStatus, VehicleType

DRIVERS = [
    Driver(
        driver_id="D001",
        full_name="Daniel",
        phone_number="0911000001",
        latitude=8.9806,
        longitude=38.7578,
        vehicle_type=VehicleType.PREMIUM,
        vehicle_model="Toyota Camry",
        vehicle_plate="AA-1001",
        status=DriverStatus.AVAILABLE,
        rating=4.9,
        completed_trips=2543,
        premium_eligible=True,
        airport_eligible=True,
        verified=True,
    ),
    Driver(
        driver_id="D002",
        full_name="Hana",
        phone_number="0911000002",
        latitude=8.9820,
        longitude=38.7600,
        vehicle_type=VehicleType.STANDARD,
        vehicle_model="Toyota Yaris",
        vehicle_plate="AA-1002",
        status=DriverStatus.BUSY,
        rating=4.8,
        completed_trips=1842,
        premium_eligible=False,
        airport_eligible=False,
        verified=True,
    ),
    Driver(
        driver_id="D003",
        full_name="Abebe",
        phone_number="0911000003",
        latitude=8.9785,
        longitude=38.7560,
        vehicle_type=VehicleType.XL,
        vehicle_model="Hyundai H1",
        vehicle_plate="AA-1003",
        status=DriverStatus.AVAILABLE,
        rating=4.95,
        completed_trips=3110,
        premium_eligible=False,
        airport_eligible=True,
        verified=True,
    ),
]
