from types import MappingProxyType

# Infrastructure permissions only. Product and operations role matrices require
# explicit CEO/CTO policy approval and are not seeded by this mission.
PERMISSION_REGISTRY = MappingProxyType(
    {
        "authorization.permissions.read": "Read the authorization permission registry.",
        "authorization.roles.read": "Read authorization roles and their grants.",
        "authorization.roles.manage": "Create roles and manage role permissions.",
        "authorization.assignments.read": "Read identity role assignments.",
        "authorization.assignments.manage": "Assign and revoke identity roles.",
        "identity.account.activate": "Activate a pending canonical platform account.",
        "identity.account.suspend": "Suspend a canonical platform account.",
        "identity.account.unlock": "Unlock a locked canonical platform account.",
        "identity.account.close": "Close a canonical platform account.",
        "identity.roles.manage": "Assign and remove approved account-native platform roles.",
        "identity.sessions.revoke": "Revoke account-native platform sessions.",
        "identity.ownership.override": "Apply an explicit administrative ownership override.",
        "identity.account.force_credential_change": "Require replacement of an Account credential.",
        "identity.session.revoke_any": "Revoke another Account's platform sessions.",
        "identity.recovery.revoke": "Revoke an Account recovery instrument.",
        "identity.role.assign": "Assign an approved account-native platform role.",
        "identity.role.remove": "Remove an approved account-native platform role.",
        "identity.bootstrap.execute": "Execute separately approved identity bootstrap tooling.",
        "support.case.create": "Create a support case with approved structured details.",
        "support.case.read_assigned": "Read only support cases assigned to the service identity.",
        "support.case.update": "Update approved fields on an assigned support case.",
        "support.case.escalate": "Escalate a support case to trained human support.",
        "support.trip.read_limited": "Read the minimum approved trip support view.",
        "support.payment.read_status": "Read payment status without credentials or mutation authority.",
        "support.account.read_limited": "Read the minimum approved account support view.",
        "support.guidance.provide": "Provide approved low-risk support guidance.",
        "support.queue.general.access": "Access support cases assigned to the general queue.",
        "support.queue.safety.access": "Access restricted safety support cases.",
        "support.queue.fraud.access": "Access restricted fraud support cases.",
        "support.queue.finance.access": "Access restricted finance support cases.",
        "support.queue.identity.access": "Access restricted identity support cases.",
        "support.queue.legal.access": "Access restricted legal support cases.",
        "dispatch.rider.request": "Create and recover the authenticated rider's rides.",
        "dispatch.driver.offer.respond": "Read and respond to the authenticated driver's offers.",
        "dispatch.worker.recover": "Run bounded server-side dispatch recovery.",
        "dispatch.admin.health.read": "Read internal dispatch worker health.",
        "scheduled.rider.create": "Create a scheduled reservation as the authenticated booker.",
        "scheduled.reservation.read": "Read an owned scheduled reservation.",
        "scheduled.reservation.manage": "Update, confirm or cancel an owned reservation.",
        "scheduled.driver.commitment.respond": "Respond to an authenticated driver's commitment.",
        "scheduled.support.handoff": "Create an authorized assisted-booking support handoff.",
        "scheduled.worker.run": "Run bounded scheduled-dispatch workers.",
        "scheduled.worker.health.read": "Read scheduled worker health.",
        "active_ride.read": "Read an owned active ride projection and event stream.",
        "active_ride.rider.command": "Submit an authenticated rider active-ride command.",
        "active_ride.driver.command": "Submit an assigned driver active-ride command.",
        "active_ride.worker.run": "Run bounded active-ride recovery workers.",
        "active_ride.worker.health.read": "Read active-ride worker health.",
        "active_ride.internal.start": "Create an Active Ride from an authoritative assignment.",
        "arrival_waiting.read": "Read an owned arrival and waiting projection.",
        "arrival_waiting.rider.command": "Submit an owned rider arrival/waiting command.",
        "arrival_waiting.driver.command": "Submit an assigned driver arrival/waiting command.",
        "arrival_waiting.worker.run": "Run bounded arrival/waiting recovery work.",
        "driver_trust.read_own": "Read the authenticated driver's onboarding projection.",
        "driver_trust.evidence.read_own": "Read privacy-minimised own evidence metadata.",
        "driver_trust.evidence.read_sensitive": "Read separately authorized sensitive evidence metadata.",
        "driver_trust.review": "Perform an authorized operations review decision.",
        "driver_trust.appeal.review": "Review a linked driver identity appeal.",
        "ride_request.create": "Create an authenticated rider's Immediate Standard request.",
        "ride_request.read_own": "Read the authenticated rider's canonical request.",
        "ride_request.cancel_own": "Cancel the authenticated rider's pre-dispatch request.",
        "ride_request.support.read": "Read an explicitly authorized support projection.",
        "dispatch.handoff.receive": "Receive an authenticated internal canonical request handoff.",
        "dispatch.handoff.worker": "Run bounded Immediate Dispatch handoff work.",
        "dispatch.driver_mode.manage_own": "Start and stop the authenticated driver's Ride Driver mode.",
        "dispatch.canonical.offer.respond": "Read and respond to the authenticated driver's canonical Immediate offer.",
        "localization.preference.read_own": "Read the authenticated identity's language preference.",
        "localization.preference.update_own": "Update the authenticated identity's language preference.",
        "pricing.policy.manage": "Create and approve immutable pricing policy versions.",
        "pricing.policy.publish": "Publish a checker-approved pricing policy version.",
        "pricing.estimate.create": "Create an owned Immediate Standard ETB estimate.",
        "pricing.estimate.accept": "Accept an owned unexpired fare estimate.",
        "pricing.final.calculate": "Calculate a final fare from a completed canonical ride.",
        "pricing.breakdown.read_own": "Read an authorized role-safe pricing breakdown.",
        "pricing.trace.read": "Read an authorized immutable financial journey projection.",
        "payment.intent.create": "Create a provider-neutral payment intent for an owned ride.",
        "payment.intent.read_own": "Read owned payment intent and attempt status.",
        "payment.attempt.execute": "Execute a provider-neutral payment attempt transition.",
        "payment.callback.ingest": "Ingest a verified provider callback envelope with replay protection.",
        "payment.reconciliation.run": "Run bounded payment reconciliation transitions for outcome_unknown attempts.",
        "payment.trace.read": "Read immutable payment traceability, events and replay views.",
        "refund.request.create": "Create an immutable refund or adjustment request for an owned ride payment.",
        "refund.review.perform": "Perform support review transitions on a refund request.",
        "refund.investigation.perform": "Record risk investigation findings and evidence on a refund request.",
        "refund.approve": "Approve refund requests for finance-authorized outcomes.",
        "refund.schedule": "Schedule approved refund requests for bounded workflow completion.",
        "refund.workflow.run": "Execute bounded service-side completion transitions.",
        "refund.trace.read": "Read immutable refund requests, decisions, authorizations, and evidence.",
        "support.refund.read_status": "Read refund request status without mutation authority.",
        "settlement.batch.create": "Create an immutable settlement reconciliation batch.",
        "settlement.collect.run": "Collect provider-neutral batch items for reconciliation.",
        "settlement.reconcile.run": "Run bounded reconciliation and exception classification.",
        "settlement.ready.approve": "Approve a balanced batch for settlement readiness.",
        "settlement.ready.reject": "Reject or revoke settlement readiness approval evidence.",
        "settlement.evidence.record": "Record authenticated provider-neutral settlement evidence without executing money movement.",
        "settlement.exception.investigate": "Investigate reconciliation exceptions and record manual review outcomes.",
        "settlement.trace.read": "Read immutable settlement and reconciliation traces.",
        "support.settlement.read_status": "Read settlement and reconciliation status without mutation authority.",
        "wallet.event.consume": "Consume an authoritative financial lineage event into immutable wallet history.",
        "wallet.account.read_own": "Read own ETB wallet balances and immutable history.",
        "wallet.trace.read": "Read immutable wallet lineage and replay-safe event projections.",
        "support.wallet.read_status": "Read wallet status without mutation authority.",
        "financial.posting.create": "Create an immutable balanced financial posting from authoritative lineage.",
        "financial.posting.trace.read": "Read immutable financial posting traces and replay-safe views.",
        "support.financial_posting.read_status": "Read financial posting status without mutation authority.",
        "financial.hold.create": "Create a financial hold that can block future money movement.",
        "financial.hold.review": "Move a financial hold into or out of under-review state.",
        "financial.hold.release": "Release a financial hold and allow future execution paths.",
        "financial.hold.escalate": "Escalate a financial hold for higher-authority manual review.",
        "financial.hold.expire": "Expire a financial hold based on authorized control policy.",
        "financial.hold.cancel": "Cancel a financial hold before release when justified.",
        "financial.hold.trace.read": "Read immutable financial hold traces and replay-safe views.",
        "support.financial_hold.read_status": "Read financial hold status without mutation authority.",
        "ledger.book.manage": "Create and archive immutable ledger books and accounts.",
        "ledger.journal.post": "Post an immutable balanced ledger journal.",
        "ledger.journal.compensate": "Post a compensating ledger journal linked to a predecessor.",
        "ledger.trace.read": "Read immutable ledger traceability and replay projections.",
        "post_trip.read_own": "Read an owned post-trip summary and receipt.",
        "post_trip.cash.confirm": "Confirm own cash paid or received evidence.",
        "post_trip.rating.create": "Submit one private rating for a completed owned trip.",
        "post_trip.internal.finalize": "Finalize and settle an authoritative completed trip.",
        "merchant.register_own": "Create a merchant profile owned by the authenticated identity.",
        "merchant.manage_own": "Manage an owned merchant profile, branches, verification and catalogue.",
        "merchant.dashboard.read_own": "Read the minimized dashboard for an owned merchant profile.",
        "merchant.assist": "Assist merchant onboarding without owning merchant credentials.",
        "merchant.verification.review": "Review staged merchant verification evidence.",
        "merchant.catalogue.review": "Review merchant catalogue readiness without publishing commerce.",
        "merchant.program.manage": "Configure bounded merchant partner programmes.",
        "catalogue.manage_own": "Create and manage catalogue records for an owned merchant.",
        "catalogue.read_own": "Read and search catalogue records for an owned merchant.",
        "ordering.create_own": "Create a canonical commerce order for the authenticated customer.",
        "ordering.read_own": "Read a canonical commerce order owned by the authenticated customer.",
        "merchant_orders.read_own": "Read canonical orders belonging to an owned approved merchant.",
        "merchant_orders.decide_own": "Accept or reject a canonical order belonging to an owned approved merchant.",
        "merchant_preparation.read_own": "Read preparation evidence for an owned approved merchant order.",
        "merchant_preparation.manage_own": "Manage preparation for an owned approved merchant order.",
        "merchant_preparation.admit": "Admit accepted orders into PRE-PRODUCTION canonical Preparation.",
        "merchant_preparation.observe_overdue": "Record PRE-PRODUCTION preparation overdue evidence.",
        "courier_dispatch.read_own_merchant": "Read courier assignment status for an owned merchant order.",
        "courier_dispatch.respond_offer": "Respond to a courier offer using authenticated courier identity.",
        "courier_pickup.read_own_merchant": "Read arrival evidence for an owned merchant order.",
        "courier_pickup.acknowledge_own_merchant": "Acknowledge courier arrival for an owned merchant order.",
        "courier_pickup.manage_assigned": "Manage arrival state as the assigned authenticated courier.",
        "courier_pickup.correct_assigned": "Correct assigned-courier arrival evidence append-only.",
        "courier_pickup.close_assigned": "End an assigned Pickup attempt before custody.",
        "courier_pickup.correct_own_merchant": "Correct merchant acknowledgement evidence append-only.",
        "courier_pickup.close_own_merchant": "End an owned-merchant Pickup attempt before custody.",
        "custody.read_own_merchant": "Read custody evidence for an owned merchant order.",
        "custody.release_own_merchant": "Seal and release an owned merchant order.",
        "custody.accept_assigned": "Verify pickup and accept custody as the assigned courier.",
        "delivery.read_own": "Read delivery credential for the authenticated customer order.",
        "delivery.manage_assigned": "Manage delivery as its assigned authenticated courier.",
        "delivery.confirm_receipt": "Confirm receipt as the authenticated ordering customer.",
        "field_operations.partner.manage": "Create and administer field partner operational profiles.",
        "field_operations.configuration.manage": "Manage field roles and territories.",
        "field_operations.assignment.manage": "Assign field partners to roles and territories.",
        "field_operations.case.manage": "Manage own territory-scoped assistance cases.",
        "field_operations.activity.record": "Record own authorized field activity evidence.",
        "field_operations.dashboard.read_own": "Read own field operations dashboard.",
        "field_operations.partner.verify": "Verify minimum public field partner status from QR evidence.",
        "field_operations.case.confirm_owner": "Confirm assisted work as the authenticated owner.",
        "field_operations.case.review": "Independently review submitted assistance cases.",
        "field_operations.quality.record": "Record immutable professional conduct evidence.",
        "field_operations.quality.read": "Read bounded Field Operations quality metrics.",
        "field_performance.evidence.record": "Record authoritative representative performance evidence.",
        "field_performance.readiness.record": "Record representative readiness assertions.",
        "field_performance.recommend": "Prepare non-executing performance recommendations.",
        "field_performance.read_own": "Read the authenticated representative's own performance view.",
        "field_performance.management.read": "Read bounded management performance summaries.",
        "mobility.service_area.create": "Create a PRE-PRODUCTION planned passenger-mobility service area.",
        "mobility.service_area.manage": "Manage PRE-PRODUCTION service-area and product availability.",
        "mobility.service_area.evaluate": "Evaluate passenger-mobility service availability.",
        "access.provenance.manage": "Manage PRE-PRODUCTION source adapters and channel capability declarations.",
        "access.provenance.record": "Record immutable accepted interaction provenance.",
        "access.provenance.support": "Record approved support-assisted interaction provenance.",
    }
)

AI_SUPPORT_PERMISSION_SET = frozenset(
    {
        "support.case.create",
        "support.case.read_assigned",
        "support.case.update",
        "support.case.escalate",
        "support.trip.read_limited",
        "support.payment.read_status",
        "support.account.read_limited",
        "support.guidance.provide",
    }
)
