import assert from 'node:assert/strict';
import test from 'node:test';

import {BookingContractError,createBookingPreviewWireRequest,parseBookingPlaces,parseBookingPreview,parseBookingPreviewInput,parseGeneratedBookingIdentifiers,sameBookingPreviewInput} from '../domain/booking-contracts.ts';

const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const hash='a'.repeat(64),now=Date.parse('2030-01-01T00:00:00Z');
const location=()=>({coordinate:{latitude:9,longitude:38},source:'rider_selected',observed_at:'2030-01-01T00:00:00Z',accuracy_metres:null,structured_address:'Addis Ababa',landmark_reference:null,note:null,map_confidence_bps:9000});
const input=()=>({pickup:{...location(),entrance_reference:null,exact_stop_reference:null,airport_terminal_reference:null,airport_zone_reference:null,reference_photo_metadata_reference:null,safety_status:'unverified',policy_version:'pickup.v1'},destination:location(),service_type:'immediate_standard'});
const preview=()=>({evidence_id:ids[0],evidence_hash:hash,pickup:'A',destination:'B',geometry:[[9,38],[9.1,38.1]],distance_metres:1,duration_seconds:1,traffic_state:'available',toll_state:'none_evidenced',toll_amount_minor:null,toll_message:null,quote_id:ids[1],currency:'ETB',estimated_fare_minor:100,pricing_version:'v1',fare_explanation:['Base'],surge_applied:false,expires_at:'2030-01-01T00:00:01Z',attribution:'test',consent:{required_version:'policy.v1',document_id:'policy.doc',content_hash:hash,acknowledgment_required:true}});
const generated=()=>parseGeneratedBookingIdentifiers({intentId:ids[0],clientPreviewId:ids[1],bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]});

test('strict request normalization creates an exact deeply frozen backend request',()=>{const original=input();const parsed=parseBookingPreviewInput(original);const wire=createBookingPreviewWireRequest(parsed,generated());original.pickup.coordinate.latitude=10;original.destination.structured_address='changed';assert.equal(wire.pickup.coordinate.latitude,9);assert.equal(wire.destination.structured_address,'Addis Ababa');assert.ok(Object.isFrozen(wire));assert.ok(Object.isFrozen(wire.pickup));assert.ok(Object.isFrozen(wire.pickup.coordinate));assert.ok(Object.isFrozen(wire.destination.coordinate));assert.ok(sameBookingPreviewInput(parsed,parseBookingPreviewInput(input())));});

test('plain-record validation rejects prototypes, accessors, symbols, inherited fields and boxed values without invoking getters',()=>{let invoked=0;const getter={...input()};Object.defineProperty(getter,'pickup',{enumerable:true,get(){invoked+=1;return input().pickup;}});const symbol={...input(),[Symbol('extra')]:true};const custom=Object.assign(Object.create({inherited:true}),input());const nullPrototype=Object.assign(Object.create(null),input());class Candidate{pickup=input().pickup;destination=input().destination;service_type='immediate_standard';}const nonEnumerable={...input()};Object.defineProperty(nonEnumerable,'pickup',{value:input().pickup,enumerable:false});for(const value of [getter,symbol,custom,nullPrototype,new Candidate(),nonEnumerable,[],()=>input(),new String('value')])assert.throws(()=>parseBookingPreviewInput(value),BookingContractError);assert.equal(invoked,0);});

test('nested records reject getters, symbols and custom prototypes without executing accessors',()=>{let invoked=0;const nested={latitude:9,longitude:38};Object.defineProperty(nested,'latitude',{enumerable:true,get(){invoked+=1;return 9;}});const symbol={...location().coordinate,[Symbol('extra')]:1};const inherited=Object.assign(Object.create({latitude:9}),{longitude:38});for(const coordinate of [nested,symbol,inherited])assert.throws(()=>parseBookingPreviewInput({...input(),destination:{...location(),coordinate}}),BookingContractError);assert.equal(invoked,0);});

test('request rejects missing, extra, malformed, circular, unsafe and non-finite input',()=>{const circular:Record<string,unknown>={};circular.coordinate=circular;for(const bad of [{...input(),extra:1},{pickup:null,destination:location(),service_type:'immediate_standard'},{...input(),pickup:{...input().pickup,source:'other'}},{...input(),pickup:{...input().pickup,coordinate:{latitude:NaN,longitude:38}}},{...input(),destination:{...location(),observed_at:'2030-01-01T00:00:00'}},{...input(),destination:{...location(),observed_at:'2030-02-30T00:00:00Z'}},{...input(),destination:{...location(),structured_address:'unsafe\u0085text'}},{...input(),pickup:{...input().pickup,policy_version:'INVALID'}},{...input(),pickup:circular}])assert.throws(()=>parseBookingPreviewInput(bad),BookingContractError);});

test('generated identifiers enforce UUID, booking-session and immediate-collision constraints',()=>{assert.equal(generated().bookingSession,ids[2]);for(const bad of [{intentId:'bad',clientPreviewId:ids[1],bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]},{intentId:ids[0],clientPreviewId:'bad',bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]},{intentId:ids[0],clientPreviewId:ids[1],bookingSession:'short',pickupId:ids[3],destinationId:ids[4]},{intentId:ids[0],clientPreviewId:ids[1],bookingSession:'x'.repeat(129),pickupId:ids[3],destinationId:ids[4]},{intentId:ids[0],clientPreviewId:ids[1],bookingSession:'x'.repeat(31)+'!',pickupId:ids[3],destinationId:ids[4]},{intentId:ids[0],clientPreviewId:ids[1],bookingSession:ids[2],pickupId:'bad',destinationId:ids[4]},{intentId:ids[0],clientPreviewId:ids[1],bookingSession:ids[2],pickupId:ids[3],destinationId:'bad'},{intentId:ids[0],clientPreviewId:ids[0],bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]}])assert.throws(()=>parseGeneratedBookingIdentifiers(bad),BookingContractError);});

test('place parser enforces exact fields, string bounds, enums, coordinates and strict booleans',()=>{const place={place_reference:'place-001',display_name:'A',secondary_text:null,kind:'address',latitude:9,longitude:38,verified_for_pickup:true,verified_for_dropoff:false,attribution:'x'};const maximum={...place,place_reference:'p'.repeat(128),display_name:'d'.repeat(160),secondary_text:'s'.repeat(160),kind:'transport_hub',attribution:'a'.repeat(160)};assert.equal(parseBookingPlaces([place,maximum]).length,2);for(const bad of [[{...place,place_reference:'short'}],[{...place,display_name:''}],[{...place,display_name:'x'.repeat(161)}],[{...place,kind:'future'}],[{...place,longitude:-181}],[{...place,longitude:181}],[{...place,latitude:Infinity}],[{...place,display_name:'bad\u0085text'}],[{...place,verified_for_pickup:1}],[{...place,extra:1}],[{display_name:'A'}],Array.from({length:11},()=>place)])assert.throws(()=>parseBookingPlaces(bad),BookingContractError);});

test('preview accepts exact backend metric, geometry, money, toll and timestamp boundaries',()=>{const maximum={...preview(),pickup:'p'.repeat(512),destination:'d'.repeat(512),geometry:Array.from({length:512},(_,index)=>[index%2?90:-90,index%2?180:-180]),distance_metres:2_000_000,duration_seconds:172_800,toll_state:'available',toll_amount_minor:10_000_000_000,estimated_fare_minor:10_000_000_000,pricing_version:'v'.repeat(63),fare_explanation:Array.from({length:16},()=> 'x'.repeat(160)),attribution:'a'.repeat(160),expires_at:'2030-01-01T03:00:01+03:00',consent:{required_version:'a00',document_id:'a00',content_hash:hash,acknowledgment_required:true}};const parsed=parseBookingPreview(maximum,now);assert.equal(parsed.currency,'ETB');assert.equal(parsed.consent.contentHash,hash);for(const valid of [{...preview(),toll_state:'unknown',toll_message:'Unavailable'},{...preview(),toll_state:'unsupported',toll_message:'Unavailable'}])assert.equal(parseBookingPreview(valid,now).currency,'ETB');});

test('preview rejects malformed identity, consent, strings, timestamps and exact expiry',()=>{for(const bad of [{...preview(),extra:1},{...preview(),expires_at:'2030-01-01T00:00:00Z'},{...preview(),expires_at:'2030-02-30T00:00:01Z'},{...preview(),expires_at:'2030-01-01T00:00:01'},{...preview(),expires_at:'2030-01-01T00:00:01+14:01'},{...preview(),consent:null},{...preview(),consent:{...preview().consent,required_version:'A00'}},{...preview(),consent:{...preview().consent,document_id:'x'}},{...preview(),consent:{...preview().consent,acknowledgment_required:1}},{...preview(),consent:{...preview().consent,content_hash:'A'.repeat(64)}},{...preview(),evidence_id:'bad'},{...preview(),evidence_hash:'A'.repeat(64)},{...preview(),currency:'USD'},{...preview(),pricing_version:'Bad Version'},{...preview(),pickup:''},{...preview(),destination:'x'.repeat(513)},{...preview(),attribution:'bad\u0085text'}])assert.throws(()=>parseBookingPreview(bad,now),BookingContractError);});

test('preview rejects invalid metrics, geometry and enum values',()=>{for(const bad of [{...preview(),traffic_state:'future'},{...preview(),toll_state:'future'},{...preview(),geometry:[[9,38]]},{...preview(),geometry:Array.from({length:513},()=>[9,38])},{...preview(),geometry:[[NaN,38],[9,38]]},{...preview(),geometry:[[9,Infinity],[9,38]]},{...preview(),geometry:[[91,38],[9,38]]},{...preview(),distance_metres:0},{...preview(),distance_metres:1.5},{...preview(),distance_metres:Infinity},{...preview(),distance_metres:2_000_001},{...preview(),duration_seconds:-1},{...preview(),duration_seconds:0},{...preview(),duration_seconds:1.5},{...preview(),duration_seconds:Infinity},{...preview(),duration_seconds:NaN},{...preview(),duration_seconds:172_801},{...preview(),estimated_fare_minor:-1},{...preview(),estimated_fare_minor:1.5}])assert.throws(()=>parseBookingPreview(bad,now),BookingContractError);});

test('preview rejects every contradictory or malformed toll combination',()=>{for(const bad of [{...preview(),toll_state:'available',toll_amount_minor:null},{...preview(),toll_state:'available',toll_amount_minor:-1},{...preview(),toll_state:'available',toll_amount_minor:1.5},{...preview(),toll_state:'available',toll_amount_minor:10_000_000_001},{...preview(),toll_state:'available',toll_amount_minor:1,toll_message:'unexpected'},{...preview(),toll_state:'unsupported',toll_message:null},{...preview(),toll_state:'unsupported',toll_amount_minor:1,toll_message:'Unavailable'},{...preview(),toll_state:'none_evidenced',toll_amount_minor:1},{...preview(),toll_state:'none_evidenced',toll_message:'unexpected'}])assert.throws(()=>parseBookingPreview(bad,now),BookingContractError);});

test('preview rejects malformed fare explanations and accessor-bearing response records',()=>{let invoked=0;const getter={...preview()};Object.defineProperty(getter,'pickup',{enumerable:true,get(){invoked+=1;return 'A';}});for(const bad of [{...preview(),fare_explanation:[]},{...preview(),fare_explanation:Array.from({length:17},()=> 'x')},{...preview(),fare_explanation:['']},{...preview(),fare_explanation:['x'.repeat(161)]},{...preview(),fare_explanation:['bad\ntext']},getter])assert.throws(()=>parseBookingPreview(bad,now),BookingContractError);assert.equal(invoked,0);});

test('preview expiry is strict immediately before, at and after the controlled clock',()=>{const expires='2030-01-01T00:00:00.001Z';assert.equal(parseBookingPreview({...preview(),expires_at:expires},now).expiresAt,expires);assert.throws(()=>parseBookingPreview({...preview(),expires_at:expires},now+1),BookingContractError);assert.throws(()=>parseBookingPreview({...preview(),expires_at:expires},now+2),BookingContractError);});
