import {act,render,waitFor} from '@testing-library/react-native';
import {useLayoutEffect} from 'react';

import {BookingIntentProvider,useBookingIntent,type BookingIntentRead} from '@/contexts/booking-intent';
import {IdentitySessionProvider,type IdentitySessionServices,useIdentitySession} from '@/contexts/identity-session';
import type {AuthenticatedSession} from '@/domain/auth-session';
import type {BookingPreviewInput} from '@/domain/booking-contracts';
import {AuthenticationApi} from '@/services/authentication-api';
import type {BookingPreviewTransport} from '@/services/booking-intent-controller';
import {SecureSessionVault,type CredentialStore} from '@/services/secure-session';
import {SessionManager} from '@/services/session-manager';

const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const hash='a'.repeat(64),now=Date.parse('2030-01-01T00:00:00Z');
const originalSession:AuthenticatedSession={identityId:'66666666-6666-4666-8666-666666666666',sessionId:'77777777-7777-4777-8777-777777777777',identityKind:'rider',accessToken:'a'.repeat(64),accessExpiresAt:'2099-01-01T01:00:00Z',refreshToken:'r'.repeat(64),refreshExpiresAt:'2099-01-02T00:00:00Z'};
const nextSession:AuthenticatedSession={...originalSession,identityId:'88888888-8888-4888-8888-888888888888',sessionId:'99999999-9999-4999-8999-999999999999',accessToken:'b'.repeat(64),refreshToken:'s'.repeat(64)};
const credentials={contactKind:'email' as const,contact:'person@example.test',password:'synthetic-password'};
const location=()=>({coordinate:{latitude:9,longitude:38},source:'rider_selected' as const,observed_at:'2030-01-01T00:00:00Z',accuracy_metres:null,structured_address:'Addis',landmark_reference:null,note:null,map_confidence_bps:9000});
const input:BookingPreviewInput={pickup:{...location(),entrance_reference:null,exact_stop_reference:null,airport_terminal_reference:null,airport_zone_reference:null,reference_photo_metadata_reference:null,safety_status:'unverified',policy_version:'pickup.v1'},destination:location(),service_type:'immediate_standard'};
const response=()=>({evidence_id:ids[0],evidence_hash:hash,pickup:'A',destination:'B',geometry:[[9,38],[9.1,38.1]],distance_metres:1,duration_seconds:1,traffic_state:'available',toll_state:'none_evidenced',toll_amount_minor:null,toll_message:null,quote_id:ids[1],currency:'ETB',estimated_fare_minor:1,pricing_version:'v1',fare_explanation:['Base'],surge_applied:false,expires_at:'2030-01-01T00:00:01Z',attribution:'test',consent:{required_version:'policy.v1',document_id:'policy.doc',content_hash:hash,acknowledgment_required:true}});
function sequence(){let index=0;return()=>ids[index++];}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
class MemoryCredentials implements CredentialStore{value:string|null=null;async get(){return this.value;}async set(_key:string,value:string){this.value=value;}async remove(){this.value=null;}}
async function identityServices(initial:AuthenticatedSession=originalSession){
  const store=new MemoryCredentials(),vault=new SecureSessionVault(store);await vault.save(initial);
  const wireSession={identity_id:nextSession.identityId,session_id:nextSession.sessionId,identity_type:nextSession.identityKind,access_token:nextSession.accessToken,access_expires_at:nextSession.accessExpiresAt,refresh_token:nextSession.refreshToken,refresh_expires_at:nextSession.refreshExpiresAt,token_type:'Bearer'};
  const request:typeof fetch=async(request,init)=>{const path=typeof request==='string'?request:request instanceof URL?request.href:request.url;if(path.endsWith('/api/auth/activation'))return new Response(JSON.stringify({activated:true}),{status:200});if(path.endsWith('/api/auth/sign-out'))return new Response(null,{status:204});if(path.endsWith('/api/auth/sign-in'))return new Response(JSON.stringify(wireSession),{status:200});throw new Error(`unexpected_auth_path:${init?.method??'GET'}`);};
  const api=new AuthenticationApi('https://api.example.test',{deviceId:'device-test',operatingSystemFamily:'test',applicationVersion:'test'},request);
  return{api:Promise.resolve(api),manager:Promise.resolve(new SessionManager(vault,api))} satisfies IdentitySessionServices;
}
let read!:BookingIntentRead,session!:ReturnType<typeof useIdentitySession>;
function Observer(){const booking=useBookingIntent(),identity=useIdentitySession();useLayoutEffect(()=>{read=booking;session=identity;},[booking,identity]);return null;}
async function mount(transport:BookingPreviewTransport,options:{generator?:()=>string;clock?:()=>number}={}){const services=await identityServices();const mounted=await render(<IdentitySessionProvider services={services}><BookingIntentProvider previewTransport={transport} identifierGenerator={options.generator??sequence()} clock={options.clock??(()=>now)}><Observer/></BookingIntentProvider></IdentitySessionProvider>);await waitFor(()=>expect(session.status).toBe('authenticated'));return mounted;}

test('real authenticated provider mount is inert and context exposes no construction or state authority',async()=>{const preview=jest.fn(async()=>response());const mounted=await mount({preview});expect(preview).not.toHaveBeenCalled();expect(Object.keys(read).sort()).toEqual(['begin','clear','requestPreview','retire','state']);for(const forbidden of ['confirm','recover','controller','store','continuity','intentId','clientPreviewId','bookingSession','stateWriter'])expect(read).not.toHaveProperty(forbidden);await act(async()=>mounted.unmount());});

test('provider preview uses its authenticated continuity and atomically locks',async()=>{const preview=jest.fn(async()=>response());const mounted=await mount({preview});await act(async()=>{read.begin(input);});let outcome;await act(async()=>{outcome=await read.requestPreview(input);});expect(outcome).toMatchObject({outcome:'confirmation_locked'});expect(read.state).toMatchObject({status:'confirmation_locked',success:false});await act(async()=>mounted.unmount());});

test.each([false,true])('real identity replacement erases state and suppresses late completion (failure=%s)',async(fail)=>{const gate=deferred<unknown>();let aborts=0;const preview=jest.fn((_request:unknown,signal?:AbortSignal)=>{signal?.addEventListener('abort',()=>{aborts+=1;},{once:true});return gate.promise;});const mounted=await mount({preview});await act(async()=>{read.begin(input);});let pending!:ReturnType<BookingIntentRead['requestPreview']>;await act(async()=>{pending=read.requestPreview(input);});await act(async()=>{await session.signOut();});expect(read.state.status).toBe('retired');fail?gate.reject(new Error('late')):gate.resolve(response());await expect(pending).resolves.toMatchObject({outcome:'superseded'});expect(aborts).toBe(1);expect(read.state.status).toBe('retired');await act(async()=>{await session.signIn(credentials);});expect(session.identity?.identityId).toBe(nextSession.identityId);expect(read.state.status).toBe('retired');await act(async()=>mounted.unmount());});

test('unmount during preview aborts once and publishes nothing afterward',async()=>{const gate=deferred<unknown>();let aborts=0;const preview=jest.fn((_request:unknown,signal?:AbortSignal)=>{signal?.addEventListener('abort',()=>{aborts+=1;},{once:true});return gate.promise;});const mounted=await mount({preview});await act(async()=>{read.begin(input);});let pending!:ReturnType<BookingIntentRead['requestPreview']>;await act(async()=>{pending=read.requestPreview(input);});await act(async()=>mounted.unmount());gate.resolve(response());await expect(pending).resolves.toMatchObject({outcome:'retired'});expect(aborts).toBe(1);expect(preview).toHaveBeenCalledTimes(1);});

test('legitimate preview dependency replacement retires old engine without a mount request',async()=>{const gate=deferred<unknown>();let aborts=0;const first:BookingPreviewTransport={preview:jest.fn((_request,signal?:AbortSignal)=>{signal?.addEventListener('abort',()=>{aborts+=1;},{once:true});return gate.promise;})};const second:BookingPreviewTransport={preview:jest.fn(async()=>response())};const services=await identityServices(),generator=sequence();const tree=(transport:BookingPreviewTransport)=><IdentitySessionProvider services={services}><BookingIntentProvider previewTransport={transport} identifierGenerator={generator} clock={()=>now}><Observer/></BookingIntentProvider></IdentitySessionProvider>;const mounted=await render(tree(first));await waitFor(()=>expect(session.status).toBe('authenticated'));await act(async()=>{read.begin(input);});let pending!:ReturnType<BookingIntentRead['requestPreview']>;await act(async()=>{pending=read.requestPreview(input);});await act(async()=>{await mounted.rerender(tree(second));});gate.resolve(response());await expect(pending).resolves.toMatchObject({outcome:'retired'});expect(aborts).toBe(1);expect(second.preview).not.toHaveBeenCalled();expect(read.state.status).toBe('idle');await act(async()=>mounted.unmount());});

test('missing provider fails explicitly',async()=>{function Missing(){useBookingIntent();return null;}await expect(render(<Missing/>)).rejects.toThrow('booking_intent_provider_required');});
