import assert from 'node:assert/strict';
import test from 'node:test';

import {createBookingPreviewWireRequest,parseBookingPreviewInput,parseGeneratedBookingIdentifiers} from '../domain/booking-contracts.ts';
import {BookingApi,type BookingSessionAccess} from '../services/booking-api.ts';

const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const location=()=>({coordinate:{latitude:9,longitude:38},source:'rider_selected',observed_at:'2030-01-01T00:00:00Z',accuracy_metres:null,structured_address:'Addis',landmark_reference:null,note:null,map_confidence_bps:9000});
const input=()=>({pickup:{...location(),entrance_reference:null,exact_stop_reference:null,airport_terminal_reference:null,airport_zone_reference:null,reference_photo_metadata_reference:null,safety_status:'unverified',policy_version:'pickup.v1'},destination:location(),service_type:'immediate_standard'});
const wire=()=>{const generated=parseGeneratedBookingIdentifiers({intentId:ids[0],clientPreviewId:ids[1],bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]});return createBookingPreviewWireRequest(parseBookingPreviewInput(input()),generated);};
class Sessions implements BookingSessionAccess{token='old';refreshes=0;async accessToken(){return this.token;}async forceRefresh(expected?:string){assert.equal(expected,'old');this.refreshes+=1;this.token='new';return {accessToken:this.token};}}

test('preview uses exact path/body and one authentication refresh without identity drift',async()=>{const calls:Array<{url:string;init:RequestInit}>=[];const sessions=new Sessions();const request:typeof fetch=async(value,init)=>{calls.push({url:String(value),init:init??{}});return calls.length===1?new Response('{}',{status:401}):Response.json({raw:'response'});};const api=new BookingApi('https://api.example.test',sessions,request);assert.deepEqual(await api.preview(wire()),{raw:'response'});assert.equal(calls.length,2);assert.equal(sessions.refreshes,1);assert.equal(calls[1].url,'https://api.example.test/mobile/booking/route-previews');assert.equal(calls[1].init.method,'POST');assert.deepEqual(JSON.parse(String(calls[1].init.body)),wire());assert.deepEqual(calls[0].init.body,calls[1].init.body);assert.doesNotMatch(String(calls[1].init.body),/rider_identity/i);});
test('search is encoded and bounded and API exposes no confirmation or recovery method',async()=>{let url='';const api=new BookingApi('https://api.example.test',new Sessions(),async(value)=>{url=String(value);return Response.json([]);});assert.deepEqual(await api.search('Addis Ababa','en',5),[]);assert.match(url,/query=Addis%20Ababa/);await assert.rejects(()=>api.search('x\n','en',5),/invalid_booking_search/);assert.deepEqual(Object.getOwnPropertyNames(BookingApi.prototype).filter(name=>/confirm|recover/i.test(name)),[]);});
test('already-aborted preview performs no fetch',async()=>{let calls=0;const api=new BookingApi('https://api.example.test',new Sessions(),async()=>{calls+=1;return Response.json({});});const abort=new AbortController();abort.abort();await assert.rejects(()=>api.preview(wire(),abort.signal),/request_cancelled/);assert.equal(calls,0);});
