import assert from 'node:assert/strict';
import test from 'node:test';

import {parseBookingPreview,parseBookingPreviewInput,parseGeneratedBookingIdentifiers,createBookingPreviewWireRequest,type BookingPreviewWireRequest} from '../domain/booking-contracts.ts';
import {createDraftRecord,lockPreview,type BookingContinuity} from '../domain/booking-intent.ts';
import {BookingApi,type BookingSessionAccess} from '../services/booking-api.ts';
import {BookingIntentController,type BookingPreviewTransport} from '../services/booking-intent-controller.ts';
import {InMemoryBookingIntentStore} from '../services/booking-intent-store.ts';

const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555','66666666-6666-4666-8666-666666666666','77777777-7777-4777-8777-777777777777','88888888-8888-4888-8888-888888888888','99999999-9999-4999-8999-999999999999','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'];
const hash='a'.repeat(64),clockValue=Date.parse('2030-01-01T00:00:00Z');
const location=()=>({coordinate:{latitude:9,longitude:38},source:'rider_selected' as const,observed_at:'2030-01-01T00:00:00Z',accuracy_metres:null,structured_address:'Addis',landmark_reference:null,note:null,map_confidence_bps:9000});
const input=()=>({pickup:{...location(),entrance_reference:null,exact_stop_reference:null,airport_terminal_reference:null,airport_zone_reference:null,reference_photo_metadata_reference:null,safety_status:'unverified' as const,policy_version:'pickup.v1'},destination:location(),service_type:'immediate_standard' as const});
const response=(expiresAt='2030-01-01T00:00:01Z')=>({evidence_id:ids[0],evidence_hash:hash,pickup:'A',destination:'B',geometry:[[9,38],[9.1,38.1]],distance_metres:1,duration_seconds:1,traffic_state:'available',toll_state:'none_evidenced',toll_amount_minor:null,toll_message:null,quote_id:ids[1],currency:'ETB',estimated_fare_minor:1,pricing_version:'v1',fare_explanation:['Base'],surge_applied:false,expires_at:expiresAt,attribution:'test',consent:{required_version:'policy.v1',document_id:'policy.doc',content_hash:hash,acknowledgment_required:true}});
function sequence(values=ids){let index=0;return()=>values[index++];}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
function setup(api:BookingPreviewTransport,clock=()=>clockValue,generator=sequence()){let continuity:BookingContinuity|undefined=Object.freeze({isCurrent:()=>true});const controller=new BookingIntentController(api,()=>continuity,generator,clock);return{controller,setContinuity:(value:BookingContinuity|undefined)=>{continuity=value;}};}

test('identifiers and booking session are internally generated, stable and renewed for a new intent',async()=>{const sent:BookingPreviewWireRequest[]=[];const value=setup({preview:async request=>{sent.push(request);return response();}});value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'confirmation_locked');value.controller.clear();value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'confirmation_locked');assert.equal(sent[0].client_preview_id,ids[1]);assert.equal(sent[0].booking_session,ids[2]);assert.equal(sent[0].pickup.pickup_id,ids[3]);assert.equal(sent[0].destination.destination_id,ids[4]);assert.notEqual(sent[1].client_preview_id,sent[0].client_preview_id);assert.notEqual(sent[1].booking_session,sent[0].booking_session);});

test('invalid or throwing identifier generation leaves no state and dispatches no request',()=>{for(let invalidIndex=0;invalidIndex<5;invalidIndex+=1){let calls=0,index=0;const values=[...ids.slice(0,5)];values[invalidIndex]='invalid';const value=setup({preview:async()=>{calls+=1;return response();}},()=>clockValue,()=>values[index++]);assert.throws(()=>value.controller.begin(input()),/invalid_booking_identifiers/);assert.equal(value.controller.read().status,'idle');assert.equal(calls,0);}let calls=0;const thrown=setup({preview:async()=>{calls+=1;return response();}},()=>clockValue,()=>{throw new Error('generator failed');});assert.throws(()=>thrown.controller.begin(input()),/invalid_booking_identifiers/);assert.equal(thrown.controller.read().status,'idle');assert.equal(calls,0);});

test('immediate generated-identifier collision fails before dispatch',()=>{let calls=0;const duplicate=ids[0];const value=setup({preview:async()=>{calls+=1;return response();}},()=>clockValue,sequence([duplicate,duplicate,ids[2],ids[3],ids[4]]));assert.throws(()=>value.controller.begin(input()),/invalid_booking_identifiers/);assert.equal(calls,0);});

test('caller mutation cannot alter the normalized request during a flight',async()=>{const gate=deferred<unknown>();let sent!:BookingPreviewWireRequest;const value=setup({preview:request=>{sent=request;return gate.promise;}});const original=input();value.controller.begin(original);const pending=value.controller.preview(original);original.pickup.coordinate.latitude=80;original.destination.coordinate.longitude=-170;original.pickup.structured_address='changed';await Promise.resolve();assert.equal(sent.pickup.coordinate.latitude,9);assert.equal(sent.destination.coordinate.longitude,38);assert.equal(sent.pickup.structured_address,'Addis');gate.resolve(response());assert.equal((await pending).outcome,'confirmation_locked');});

test('identical duplicate callers share the exact promise and conflicting input fails locally',async()=>{const gate=deferred<unknown>();let calls=0;const value=setup({preview:()=>{calls+=1;return gate.promise;}});value.controller.begin(input());const first=value.controller.preview(input()),second=value.controller.preview(input());assert.equal(first,second);const changed={...input(),destination:{...location(),coordinate:{latitude:10,longitude:38}}};assert.equal((await value.controller.preview(changed)).outcome,'conflicting_request');gate.resolve(response());assert.equal((await first).outcome,'confirmation_locked');assert.equal(calls,1);});

test('synchronous transport failure clears its owned flight and a new intent dispatches independently',async()=>{let calls=0;const value=setup({preview:()=>{calls+=1;if(calls===1)throw new Error('synchronous');return Promise.resolve(response());}},()=>clockValue,sequence([...ids,...ids,...ids]));value.controller.begin(input());const first=value.controller.preview(input());assert.equal((await first).outcome,'failed_safe');value.controller.clear();value.controller.begin(input());const second=value.controller.preview(input());assert.notEqual(second,first);assert.equal((await second).outcome,'confirmation_locked');assert.equal(calls,2);value.controller.clear();value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'confirmation_locked');assert.equal(calls,3);});

test('real BookingApi malformed response fails safely and a later valid response dispatches independently',async()=>{let calls=0;class Sessions implements BookingSessionAccess{async accessToken(){return 'opaque';}async forceRefresh(){return undefined;}}const api=new BookingApi('https://api.example.test',new Sessions(),async()=>Response.json(++calls===1?{malformed:true}:response()));const value=setup(api);value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'failed_safe');assert.deepEqual(Object.keys(value.controller.read()).sort(),['safeReason','status']);value.controller.clear();value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'confirmation_locked');assert.equal(calls,2);});

test('identity replacement erases evidence and suppresses late success and failure',async()=>{for(const fail of [false,true]){const gate=deferred<unknown>();const value=setup({preview:()=>gate.promise});value.controller.begin(input());const pending=value.controller.preview(input());await Promise.resolve();value.setContinuity(Object.freeze({isCurrent:()=>true}));assert.equal(value.controller.replaceIdentity().status,'retired');fail?gate.reject(new Error('late')):gate.resolve(response());assert.equal((await pending).outcome,'superseded');assert.deepEqual(value.controller.read(),{status:'retired'});}});

test('clear during pending success or failure returns cleared and exposes no evidence',async()=>{for(const fail of [false,true]){const gate=deferred<unknown>();const value=setup({preview:()=>gate.promise});value.controller.begin(input());const pending=value.controller.preview(input());await Promise.resolve();assert.equal(value.controller.clear().status,'idle');fail?gate.reject(new Error('late')):gate.resolve(response());assert.equal((await pending).outcome,'cleared');assert.deepEqual(value.controller.read(),{status:'idle'});}});

test('retirement aborts pending success or failure and cannot revive state',async()=>{for(const fail of [false,true]){const gate=deferred<unknown>();let aborts=0;const value=setup({preview:(_request,signal)=>{signal?.addEventListener('abort',()=>{aborts+=1;},{once:true});return gate.promise;}});value.controller.begin(input());const pending=value.controller.preview(input());await Promise.resolve();value.controller.retire();fail?gate.reject(new Error('late')):gate.resolve(response());assert.equal((await pending).outcome,'retired');assert.equal(aborts,1);assert.deepEqual(value.controller.read(),{status:'retired'});}});

test('old success, failure and finalizer cannot clear or settle a newer flight',async()=>{for(const fail of [false,true]){const first=deferred<unknown>(),second=deferred<unknown>();let call=0;const value=setup({preview:()=>++call===1?first.promise:second.promise});value.controller.begin(input());const old=value.controller.preview(input());await Promise.resolve();value.controller.retire();value.controller.begin(input());const current=value.controller.preview(input());await Promise.resolve();fail?first.reject(new Error('late')):first.resolve(response());assert.equal((await old).outcome,'retired');assert.equal(value.controller.preview(input()),current);second.resolve(response());assert.equal((await current).outcome,'confirmation_locked');}});

test('abort before dispatch and after response resolution cannot publish success',async()=>{let calls=0;const before=setup({preview:async()=>{calls+=1;return response();}});before.controller.begin(input());const already=new AbortController();already.abort();assert.equal((await before.controller.preview(input(),already.signal)).outcome,'cancelled');assert.equal(calls,0);const gate=deferred<unknown>();const after=setup({preview:()=>gate.promise});after.controller.begin(input());const abort=new AbortController();const pending=after.controller.preview(input(),abort.signal);await Promise.resolve();gate.resolve(response());abort.abort();assert.equal((await pending).outcome,'cancelled');assert.deepEqual(after.controller.read(),{status:'retired'});});

test('expiry equality and cached expiry become stale under the controlled clock',async()=>{let now=clockValue;const value=setup({preview:async()=>response('2030-01-01T00:00:01Z')},()=>now);value.controller.begin(input());assert.equal((await value.controller.preview(input())).outcome,'confirmation_locked');now=Date.parse('2030-01-01T00:00:01Z');assert.equal(value.controller.read().status,'stale');const equal=setup({preview:async()=>response('2030-01-01T00:00:00Z')},()=>clockValue);equal.controller.begin(input());assert.equal((await equal.controller.preview(input())).outcome,'failed_safe');});

test('missing and invalidated continuity fail closed and erase cached evidence',async()=>{const missing=setup({preview:async()=>response()});missing.setContinuity(undefined);assert.throws(()=>missing.controller.begin(input()),/identity_unavailable/);let current=true;const continuity=Object.freeze({isCurrent:()=>current});const controller=new BookingIntentController({preview:async()=>response()},()=>continuity,sequence(),()=>clockValue);controller.begin(input());assert.equal((await controller.preview(input())).outcome,'confirmation_locked');current=false;assert.deepEqual(controller.read(),{status:'retired'});});

test('store snapshots are deeply immutable and clear removes the complete record',()=>{const parsedInput=parseBookingPreviewInput(input());const generated=parseGeneratedBookingIdentifiers({intentId:ids[0],clientPreviewId:ids[1],bookingSession:ids[2],pickupId:ids[3],destinationId:ids[4]});const request=createBookingPreviewWireRequest(parsedInput,generated);const continuity=Object.freeze({isCurrent:()=>true});const draft=createDraftRecord({intentId:generated.intentId,clientPreviewId:generated.clientPreviewId,bookingSession:generated.bookingSession,continuity,input:parsedInput,request});const locked=lockPreview({...draft,status:'previewing'},parseBookingPreview(response(),clockValue));const store=new InMemoryBookingIntentStore();store.replace(locked);const first=store.read();assert.ok(first);assert.ok(Object.isFrozen(first));assert.ok(Object.isFrozen(first.preview));assert.ok(Object.isFrozen(first.preview?.consent));assert.throws(()=>{if(first?.preview)Object.defineProperty(first.preview,'quoteId',{value:'changed'});});assert.equal(store.read()?.preview?.quoteId,ids[1]);store.clear();assert.equal(store.read(),undefined);});
